### ISSUE TITLE
Side effects when using hidden controlInput

### ISSUE THREAD

**Issue by oyejorge** [orchidjs/tom-select#140]
There are some side effects when using `controlInput` in [this way](https://github.com/orchidjs/tom-select/issues/25)

1. Setting the `<select>` to required doesn't work 
2. The `<select>` won't focus when tabbing through a form (or using arrows on iOS)

The second one is only a minor UX issue but the first is not ideal - although perhaps it could be validated in JS...

_Originally posted by @TomWFox in https://github.com/orchidjs/tom-select/issues/25#issuecomment-877297175_

**Comment by oyejorge** [comment]
Thanks for pointing that out, I should have put 2 and 2 together and realized this was an issue [when this bug came it](https://github.com/orchidjs/tom-select/issues/138).

**Comment by oyejorge** [comment]
Needed more significant changes to fix this so I've started the 2.0 version. Should be fixed with the current 2.0-Beta release

**Comment by TomWFox** [comment]
Thanks for looking into this so promptly Josh!

I tested v2.0.0-Beta.2 and it does seem to fix the required issue. Unfortunately, I'm still experiencing the second issue (`<select>` not focusing).

**Comment by oyejorge** [comment]
Right, the way to do it in v2 is just [a little different](https://jsfiddle.net/x9gfrjes/).

```js
    controlInput: null,
```
instead of
```js
    controlInput: '<input>',
````

**Comment by TomWFox** [comment]
Ah I see, thanks!
