### ISSUE TITLE
Input delay/freeze during first search

### ISSUE THREAD

**Issue by dobbidev** [orchidjs/tom-select#458]
**Describe the bug**
Input lag/freeze when typing the first time in tom-select search.

**To Reproduce**

1. Go to https://tom-select.js.org/
2. Click on the example select
3. Type something (here occurs the bug, the input lag/freeze for 0.2-0.5 seconds, but only the first time)
4. Now there is no more input lag when typing
5. reload the page
6. -> step 2

**Expected behavior**
No input lag/freeze after typing  the first time in tom-select

**Additional context**
This bug is new in version 2.1.0. It doesn´t exist in 2.0.3

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by andinger** [comment]
I have the same problem ... does anybody has ideas regarding this issue?

**Comment by oyejorge** [comment]
Should be fixed with this commit: https://github.com/orchidjs/tom-select/commit/f8f8ee2ad099f76d79d359c7188a1ff120fdbbb4

**Comment by oyejorge** [comment]
@andinger @dobbidev 
The change is live on https://tom-select.js.org, can both/either of you confirm the problem has been resolved there?

**Comment by andinger** [comment]
@oyejorge it is still not as fast as in 2.0.3 - nevertheless it has become much better. thank you 🎉

**Comment by oyejorge** [comment]
Thanks!

**Comment by djrobby** [comment]
There is still a big delay in the very initial keystroke (specifically when tied to an input field). I'd say it's easily 250-400ms. Same delay exists in the very first example on your website @ https://tom-select.js.org/examples/
